### ISSUE TITLE
No geneclusters.txt in the new version?

### ISSUE THREAD

**Issue by felipelira** [antismash/antismash#128]
Looking for this file in my outputs from Antismash, I didn't find it?
Is there any option to generate this file or it is not available in the new version?
Do you have any post-processing data script to do this?

Thank you in advance.

**Comment by SJShaw** [comment]
This was a deliberate change. The `geneclusters.txt` output file is no longer available, along with many other intermediate stage files and incomplete result files. We might consider adding something like this in the future, but it wouldn't be in the same format in any case. We've focused on three outputs:
- HTML for a fast human-readable summary and interaction (with details where possible)
- JSON for machine-readable results
- Genbank for use with typical genome viewers and as a more navigable text-only output (this does lose a little information due to the genbank format limitations)

Depending on which information you wanted from the file, it should be already available or easy for you to generate yourself. We don't have a script to generate an exact equivalent of the `geneclusters.txt` file, but feel free to use the following as inspiration:

```
from antismash.common.secmet import Record

for record in Record.from_genbank(filename, taxon="bacteria"):  # or fungi, if relevant
    for region in record.get_regions():
        for cds in region.cds_children:
            print(record.id, region.get_product_string(), cds.get_name())
```

**Comment by felipelira** [comment]
First of all, I ask for permission to paste the code I am using to extract this information. If you consider inappropriate, I remove it.
As a suggestion for the other users, I paste the script I am using to extract this kind of information.

```
import sys, os
from Bio import SeqIO

usage : python get_geneclusters.py directory_with_regions

directory = sys.argv[1]
dict_cluster = {}
for infile in sorted(os.listdir(sys.argv[1])):
	if 'region' in infile:
		for record in SeqIO.parse(os.path.join(directory,infile), "genbank"):
			for feature in record.features:
				if feature.type == "protocluster":
					product = feature.qualifiers.get("product", ["???"])[0]
					if record.id not in dict_cluster:
						dict_cluster[record.id, record.description] = [product]
					else:
						dict_cluster[record.id, record.description].append(product)
for k, v in dict_cluster.iteritems():
	print '\t'.join(k) +  '\t' +  ''.join(v)
```
