### ISSUE TITLE
No BGCs in B.thetaiotamicron

### ISSUE THREAD

**Issue by utpalmtbi** [antismash/antismash#143]
Bacteroides thetaiotaomicron VPI-5482 (NCBI assembly ID: GCA_000011065.1) has experimentally verified BGCs in their genome which is also present in MIBiG. But why I am getting no antismash results in this strain? I ran antismash both locally (conda) and in antismash server.

**Comment by SJShaw** [comment]
The MIBiG cluster (BGC0001654) is a saccharide, which antiSMASH generally considers to be primary metabolism and won't annotate by default. On the command line you can find these by adding `--hmmdetection-strictness loose` to the options. For the website, there is a selector for this option on the development site (dev.antismash.secondarymetabolites.org) that you can move to select this "loose" option (though it will detect 27 of these saccharide regions).

As for not finding other product types in the assembly, it appears that there are no other types of BGC present in the assembly that antiSMASH has rules to detect. If there's a cluster other than the saccharide that you know exists in the assembly, we can look into it if you can give us some kind of reference for where to find further information on it.

**Comment by kblin** [comment]
We'll be adding this setting to the antiSMASH web service soon. You can already test-drive this at the development preview site: https://dev.antismash.secondarymetabolites.org/#!/start
If you set the strictness-slider to "loose", antiSMASH will detect the BGC0001654-like cluster. It will however also report over 20 other primary metabolism saccharide clusters as false positives, which is why we don't run with "loose" strictness by default.

**Comment by kblin** [comment]
This is now also live on our main website.
