### ISSUE TITLE
Add back NRPS Predictor3 to the AD domain substrate prediction step

### ISSUE THREAD

**Issue by zachcp** [antismash/antismash#148]
**Is your feature request related to a problem? Please describe.**
We've noticed  on a few clusters we've been working on that the Adenylation domain substrate predictions differ in AS5 relative to AS4. 

**Describe the solution you'd like**
Would it be possible to restore the use of NRPSPredictor3 to the AS5 pipeline?

**Describe alternatives you've considered**
1. Use AS4 and AS5 in parallel on the same sequences
2. run NRPSPredictor3 ourselves

**Additional context**
Here is a breakdown of the Adenylation domain substrate differences between AS4 and AS5 on the mibig dataset:  [substrate_prediction_comparison](https://github.com/zachcp/substrate_prediction_comparison). It seems most of the differences between the two programs are related to `no_call`s which I would guess to be due to differences in acceptance thresholds. However there is also a small subset of sequences where there are differences.

**Comment by SJShaw** [comment]
That's an impressive writeup, I appreciate the effort! There's definitely some shortcomings to just using NRPSPredictor2, but we're in a 

Before anything else, the stachelhaus references for NRPSPredictor3 are identical to that of NRPSPredictor2. This is because the aS4 stachelhaus prediction didn't come from NRPSPredictor3, but from the SANDPUMA section's own implementation along with its own dataset (`antismash/specific_modules/nrpspks/sandpuma/flat/fullset0_smiles.stach.faa`). The SVM result from aS4 is from NRPSPredictor3. 

That's not to say we couldn't change the stach prediction step of NRPSPredictor.

We originally dropped SANDPUMA from aS5 because it was being rewritten by the original contributors as SANDPUMA2 in order to solve both performance problems and data problems (for instance, many predictions aren't just the A-domain substrate but the product of full module, including modification domains). We brought back NRPSPredictor2 as a placeholder. We will be having a discussion with these contributors on Thursday so we can find out what the current state is. Kai has a better handle on the data issues than I do, maybe he can chip in. If we changed the NRPSPredictor stach prediction to use the SANDPUMA data, then the data issues would return.

We've also talked about updating NRPSPredictor ourselves to a new dataset, as we know it's getting pretty old at this stage. We've also talked about taking the opportunity to move from java to python to simplify our dependencies at the same time. Even if SANDPUMA2 doesn't come through, if the data is there and ready to go, we should be able to bring it in to aS5 (though it might be as a 5.1 release, since we're in the final parts of releasing 5.0).

Once we've got the extra info from this meeting, we can try and make some plans about how we'll change the A-domain predictions and when it will be likely to happen.

**Comment by zachcp** [comment]
Thanks @SJShaw for your great work on AS5.

Your comments make a lot of sense to me and I look forward to any updates if there are any.

**Comment by kblin** [comment]
Hi Zach, thanks for your detailed analysis. One of the problems with it is that you fell into the same trap Marc fell into when collecting the SANDPUMA dataset:

Some of the A domain substrate specificities in MIBiG are wrong. They were imputed from the final compound structure, but include downstream tailoring reactions. MIBiG (and thus SANDPUMA's stachelhaus table) contains a lot of d-amino acids when the module sequence clearly contains an epimerase domain, meaning that the A domain substrate is the l-amino acid, but the final compound ends up with the d-amino acid due to the E domain. There are less than a handful described A domains that do in fact accept d-amino acids as substrates.

NRPSPredictor 3 is a bit of a misnomer, really, as it is the same program as NRPSPredictor 2, just with the single amino acid SVMs retrained with the new (slightly flawed) SANDPUMA data set. The fallback predictions of the small clusters, large clusters and broad physiochemical properties were not updated (because that update happened for SANDPUMA, and SANDPUMA's ensemble predictor only cares about single AA predictions).

That said, I understand Marc has put a lot of time into cleaning up the A domain training set for the SANDPUMA 2 update, and it's probably worth re-training  NRPSPredictor with that as well, for predictors on all levels.

**Comment by zachcp** [comment]
Thanks Kai, this clears up the issue quite a bit.  

While it may be that the misnamed NRPS3 is based on a slightly flawed datasets, it did correctly annotate a few A-domains we were interested in :) 

I agree with you that an update in training set will help and look forward to the Sandpuma release.
