### ISSUE TITLE
AttributeError: module 'scss' has no attribute 'Compiler' when  antismash --check-prereqs

### ISSUE THREAD

**Issue by atiweb** [antismash/antismash#175]
antismash --check-prereqs
Traceback (most recent call last):
  File "/usr/local/bin/antismash", line 9, in <module>
    entrypoint()
  File "antismash-5.0.0/antismash/__main__.py", line 124, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/antismash-5.0.0/antismash/__main__.py", line 113, in main
    antismash.run_antismash(sequence, options)
  File "antismash-5.0.0/antismash/main.py", line 574, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "antismash-5.0.0/antismash/main.py", line 596, in _run_antismash
    check_prerequisites(modules, options)
  File "antismash-5.0.0/antismash/main.py", line 504, in check_prerequisites
    res = module.check_prereqs(options)
  File "antismash-5.0.0/antismash/outputs/html/__init__.py", line 66, in check_prereqs
    return prepare_data()
  File "antismash-5.0.0/antismash/outputs/html/__init__.py", line 57, in prepare_data
    result = scss.Compiler(output_style="expanded").compile(flavour + ".scss")
AttributeError: module 'scss' has no attribute 'Compiler'

The file:
https://github.com/antismash/antismash/blob/master/antismash/outputs/html/__init__.py
requiere
https://github.com/Kronuz/pyScss
should be added:
pip uninstall libsass
pip uninstall scss
pip install pyScss

and in:
https://github.com/antismash/antismash/blob/master/antismash/outputs/html/__init__.py
add:
from scss import Compiler
under import scss

With that the issue is fixed

Greetings

**Comment by kblin** [comment]
Hi there, thanks for your issue report.
How did you install antiSMASH? I'm asking because we already install pyScss in [setup.py](https://github.com/antismash/antismash/blob/master/setup.py#L24). I'm wondering if there is a version issue happening or something.
I'm afraid that with the information provided, I can't reproduce the issue you are describing.

**Comment by atiweb** [comment]
Hi, I downloaded
https://dl.secondarymetabolites.org/releases/latest/antismash-5.0.0.tar.gz
and extracted it, then runned antismash, and try to solve the dependencies that was required
The main issue is that in
https://github.com/antismash/antismash/blob/master/antismash/outputs/html/__init__.py
does not have the line (from scss import Compiler)
Thank for your reply and work
Very greatfull

**Comment by SJShaw** [comment]
`import scss; scss.Compiler` and `from scss import Compiler` are (usually) functionally identical and
either should work, since [`scss.__init__`](https://github.com/Kronuz/pyScss/blame/master/scss/__init__.py#L56) imports `Compiler` explicitly for re-importing and that hasn't changed for 5 years.

Going by your first comment, you didn't install with our setup file, but manually installed scss and not pyscss to start with. That's the cause of the issue.

**Comment by atiweb** [comment]
Yes. You are right. Thanks

Em dom, 16 de jun de 2019 12:34 PM, SJShaw <notifications@github.com>
escreveu:

**Comment by atiweb** [comment]
Yes, you are right. Thanks
