### ISSUE TITLE
Is there a way to combine Antismash run results?

### ISSUE THREAD

**Issue by zachcp** [antismash/antismash#180]
Hello Team Antismash,

I am wondering if there is a way to combined Antismash results from different runs. For example - to take two JSON outputs, combine them, and then generate a new, combined html output? I played around a bit with the [AntismashResults](https://github.com/antismash/antismash/blob/master/antismash/common/serialiser.py#L24) class but it looks like Module results are either not stored or [not parsed](https://github.com/antismash/antismash/blob/d6c4499ddc54fb545b648c3640decb67e83fc406/antismash/common/module_results.py#L45) so, while I was able to load the JSON files I was unable to generate fresh html.  Is there some way to do this currently? If not, I think this might be a useful additional tool.

Regards,
zach cp

**Comment by SJShaw** [comment]
`ModuleResults` is used as an abstract base class for all the module's to use for their specific implementations. Each module rebuilds its own results (see the `regenerate_previous_results()` function in any module).

That said, it's an interesting idea. I'd hadn't considered this use when I structured everything, but it should be able to work without much effort. I'll play with it over the next day or two and will let you know what I come up with.

**Comment by SJShaw** [comment]
I've written a standalone python [script](https://gist.github.com/SJShaw/67b438c58d1f83ed261ca177b6035951) to combine JSON results. I've started with a few conditions:
- all taxons must match if present (they're optional in the result schema v.1)
- all record identifiers must be unique
- all schema versions must match and be 1 (the script would need to change for alternate schema versions)

Usage would be like:
```
./combiner.py combined.json input1.json input2.json input3.json
./run_antismash.py --reuse combined.json
```
I'm not sold on adding it to antiSMASH as an extra argument or anything, but we could add it as another standalone command, if this suits the use case you were thinking of.

**Comment by zachcp** [comment]
@SJShaw ,

Thanks for your response & code.  This is great - it lets one combine the JSON results. But the second half of the problem is to generate fresh outputs  from the newly created JSON  (html in particular, but gbks would also be nice).  

To give some context, this concatenation of results is useful when running Antismash jobs in a MAP-Reduce pattern where a single job could be a single contig/chromosome  (Map) but you want look at the aggregated results(Reduce).   I suppose I this requires round-tripping the JSON back into a full `AntismashResults` object which can regenerate fresh output files.

For example of where I run into trouble, see below. 

```python

# run your jobs

# aggregate your json files

# regenerate the html/gbk outputs from your JSON
from antismash.main import write_outputs
from antismash.common.serialiser import AntismashResults
from antismash.config import get_config, ConfigType, build_config, update_config

results = AntismashResults.from_file("combined_output.json")
options = get_config()
config  = update_config({'output_dir': "output", 'taxon': 'bacteria'})

# runnning into errors here.
write_outputs(results, config)
```

**Comment by SJShaw** [comment]
You're skipping the step in the process where all the results are regenerated and reapplied. Arguably we're missing the step in the serialiser, but that's somewhat intentional as enforcing the order in which results are reapplied is important and it's easier to be consistent by going through the same process steps as a fresh run, just reusing results where available. For example, after adding all the protocluster predictions, there have to be extra steps to regenerate the regions from those protoclusters. Any change in arguments is (generally) also respected, so clusterblast's limit could be increased or decreased and the module will use the results if it can.

For genbank files, you can concatenate the files themselves faster than using antiSMASH to do it, but obviously the HTML doesn't work that way.

Here's an alternative that I know works and is essentially the same thing as on the command line (the runtime will depend very much on how many regions are detected and how modules have results to annotate):
```
from antismash.main import run_antismash, get_all_modules
from antismash.config import build_config

config = build_config(['--output', 'combined', '--taxon', 'bacteria', '--reuse', 'combined_output.json'],
                      modules=get_all_modules())

run_antismash(None, config)
```

**Comment by zachcp** [comment]
Brilliant. I was completely unaware of this possibility;  my first test of this worked fine.

**Comment by zachcp** [comment]
Note:  it is also possible, post JSON concatenation to use antismash's new `reuse-results` CLI flag:

```bash
antismash --reuse-results combined_output.json --output-dir antismash
```

more great work from the AS5 team!
