### ISSUE TITLE
Results compatible with previous genome annotation

### ISSUE THREAD

**Issue by natJimenez** [antismash/antismash#181]
We are running antismash to find biosynthetic capabilities of different organisms, but we already have our own annotation of these genomes.
Is there a way to give our own genebank file with our annotation to generate data compatible with our own open reading frames?

**Comment by SJShaw** [comment]
If you've annotated the genes (and CDS features) in the genbank file, you can just use the genbank file as the input to antiSMASH. We try not to remove or override any annotations that we don't absolutely have to.

If you are providing a genbank file and it isn't behaving as you expect, that's different and we'd need more details in order to work out what's going on.
