### ISSUE TITLE
No structures for NRPS's in antiSMASH 5.0.0

### ISSUE THREAD

**Issue by bruc** [antismash/antismash#190]
**Describe the bug**
There are no NRPS structures drawn for an NRPS's that did get predicted structures in antiSMASH 4.

**To Reproduce**
I've installed antiSMASH-5.0.0 from the Releases section of the Github antiSMASH site and it seems to work fine. I'm using GCA_000021785.1_ASM2178v1_genomic.gbff from NCBI (Bacillus cereus) for testing. When run in antiSMASH 4, the NRPS pages show predicted structures, whereas in antiSMASH 5, I get a link to the Norine web page that doesn't work.

I noticed that the example antiSMASH output for S. coelicolor on the antiSMASH web site, the NRPS's do have structures available.

Is there something missing in the installation that I can add to get the structure prediction images? Going to the Norine web site is not useful in my context.

**Comment by kblin** [comment]
Hi Bob,

the library we used in antiSMASH 1-4 to draw structures from SMILES does not provide a python 3 version, so we've switched to rendering the structures in the HTML page using a JavaScript library.

The most basic question first: because we now possibly show multiple structures if there are multiple candidate clusters in a region, the structures are folded away by default. If you hit the + icon next to, say the `For candidate cluster 4, location 2248987 - 2297534: ` text on the side bar in region 4, does the structure display?

This works for me in Firefox locally, as well as on our servers for both the 5.0.0 release version https://antismash.secondarymetabolites.org/upload/bacteria-65dbd965-bd8b-4e9d-a1de-eb515d134721/index.html#r1c7 as well as the current development branch https://dev.antismash.secondarymetabolites.org/upload/bacteria-446d09c4-0095-4480-a679-dbedbf1484d8/index.html#r1c7

What browser are you using?

**Comment by bruc** [comment]
Hi Kai,
    I'm running Firefox ESR 52.7.3 (64-bit). I will update and try again.

    On my version of antiSMASH 5, there is no "+" sign

![image](https://user-images.githubusercontent.com/6069427/63096315-a7297b00-bf3b-11e9-97e5-89070a9f2654.png)

**Comment by SJShaw** [comment]
There's some other issue going on with your browser, as none of the images are being displayed in your screenshot apart from the dynamically generated SVGs. The logos, navigation bar icons, the help icons, the images in the zoom controls, and the expand/`+` icons are all missing.

Is that a deliberate choice?

**Comment by bruc** [comment]
No. I'm running a vanilla Firefox as far as I know. BTW, I just updated to Firefox 60.6.1 ESR.
What Firefox settings would affect the image display?
BTW, this is on Linux -- I'll try later today on some Windows browsers.

**Comment by SJShaw** [comment]
I'm using a linux firefox here and it's fine. If it's not a deliberate choice, then it is probably something with the webserver not serving images correctly.

Just as a sanity check, there should be an `images` directory with the images in it. If you replace the `index.html` in your URL with `images/bacteria_logo.png` and you get a 404/not found, then the problem is that the images are missing from the server.

**Comment by bruc** [comment]
I just tried Chrome on a Windows system -- same appearence. The web server is serving the images -- I tried the URL experiment you suggested as a sanity check. I also tried Firefox 68.0.2 on Windows -- same problems.

**Comment by SJShaw** [comment]
If you download the zip file option from the menu (or scp/rsync, whatever you'd like) to your local machine, unzip it, and view it there, do the images appear?

**Comment by bruc** [comment]
No, they do not -- great question. That implies that my web server is the issue. I'm running an old version of Apache.

Can you send me the httpd configuration files on your webserver (minus anything sensitive)

**Comment by bruc** [comment]
I think I found the problem -- the old version of Apache. I tried serving the files from httpd 2.4 (instead of 2.2) and it works now.

**Comment by bruc** [comment]
The choice of web server version would be a good thing to add to the antiSMASH documentation.

**Comment by bruc** [comment]
Could you modify the code so that the structures are displayed by default?

**Comment by SJShaw** [comment]
When a region has many candidate clusters, like below, displaying all structures (or even the first structure) is too visually noisy.
![image](https://user-images.githubusercontent.com/1700735/63167108-96a6fc80-c030-11e9-8d54-18679c14df79.png)

However, if you want to change your local version, that's easy. You'd just need to change https://github.com/antismash/antismash/blob/master/antismash/modules/nrps_pks/templates/products.html#L12 to have `level="all"` instead of `level="candidate"`.

**Comment by bruc** [comment]
Thank you for the pointer to the code as to what to change. 

You can close this issue.

**Comment by bruc** [comment]
I tried the change above, and it didn't work as expected. The symbol next to the cluster's structure line changed to "-", but no structure appeared. If I clicked on the "-" symbol twice, then the structure appeared.

**Comment by SJShaw** [comment]
You'll need to update to the development version (or at least aac523f5), as the javascript library was updated to handle these hidden elements better.

**Comment by bruc** [comment]
It works now as you had originally suggested. Thank you.
