### ISSUE TITLE
Antismash 4.2 --help says to follow the antismash call with -h, this seems to be resulting in no analysis occuring.?

### ISSUE THREAD

**Issue by Lamm-a** [antismash/antismash#213]
**Describe the bug**
I am using Antismash 4.2 due to installing via conda but the --help documentation says to use antismash -h [options] but this just results in the -h call showing all the help documentation but no other execution or analysis occuring. How can I run antismash with custom options without this -h flag? the slurm generated output log shows no errors of any kind.

**Expected behavior**
Antismash to begin analysis with the options I flagged

**System (please complete the following information):**
 - OS: Unix based cluster (genomedk)

**Comment by kblin** [comment]
Hi there,

As a first disclaimer, we don't really support antiSMASH 4 anymore. antiSMASH 5 has been out for almost a year now, is better in every aspect, and we have limited resources for support.

That said, in this particular case I think you've misunderstood the help output. the `-h` is in square brackets, meaning it's optional. In particular `--help` and `-h` is the same thing and will just show the help. If you just leave out the `-h` everything should work as expected.

Hope this helps,
Kai

**Comment by Lamm-a** [comment]
When I omit the -h flag antismash shows an error saying the optional analysis flags are not recognised. Has the conda install for antismash been updated for 5.0 yet?

**Comment by kblin** [comment]
You've got typos in the `--knownclusterblast` and `--subclusterblast` parameters.

There's problems with the conda build for antiSMASH 5, because we depend on the MEME suite for the `meme` and `fimo` commands. Unfortunately, the MEME suite itself comes with some Python parts as well (that we don't depend on), and those are Python2-based in the version of MEME we depend on, which can't easily be packaged in conda for Python3 packages such as antiSMASH 5.

See https://github.com/bioconda/bioconda-recipes/pull/17382 for the nitty-gritty details

**Comment by Lamm-a** [comment]
Oh dear so I have. My apologies!! Thank you.
That is a shame about antiSMASH5 being unlikely to come to conda then. Is there substantial differences in the power between the two?

**Comment by SJShaw** [comment]
antiSMASH5 is faster, detects more types of clusters, has fixed some prediction issues in a variety of places, and gives much better information about the composition of hybrid clusters. For details you can see the antiSMASH5 [paper](https://doi.org/10.1093/nar/gkz310) and the 5.1 [changelog](https://docs.antismash.secondarymetabolites.org/changelog/5.1/).
