### ISSUE TITLE
make header rename optional

### ISSUE THREAD

**Issue by adityabandla** [antismash/antismash#217]
**Is your feature request related to a problem? Please describe.**
Some of my genomes have long contig headers and preserving them as such is useful for downstream stats. I understand the rational behind renaming is to conform with the genbank limit, but I guess it becomes cumbersome for users who don't intend to work/submit using the genbank format

**Describe the solution you'd like**
Renaming headers should be optional

**Comment by adityabandla** [comment]
Can this be done using the --skip_sanitisation option?

**Comment by kblin** [comment]
For a while we did this because writing GenBank files using Biopython would mangle the ID lines if IDs were too long. It's probably worth checking if that is still happening. Otherwise I agree there should be an option to leave the IDs untouched.

**Comment by jcpasion** [comment]
I also would love to have this option. Is there any way this could be implemented?

Also, what are the triggers to rename the output Gbk files to "c0001" and so on? I'm trying  to change the FASTA headers so that the organism name is part of the genbank output, but it keeps defaulting to "c0001".

I've changed the headers so that the contig name is "name of strain" + "_" + "contig #"
Example:
>GCA_123456789.1_1
>GCA_123456789.1_2
...
>GCA_123456789.1_50

The contig Description is unchanged.

When the FASTA file containing these altered headers is run through antismash, I get this gbk output format:

c00001_GCA_123...region001.gbk 
c00002_GCA_123...region001.gbk 
...

Any help?

**Comment by jcpasion** [comment]
> I also would love to have this option. Is there any way this could be implemented?
> 
> Also, what are the triggers to rename the output Gbk files to "c0001" and so on? I'm trying to change the FASTA headers so that the organism name is part of the genbank output, but it keeps defaulting to "c0001".
> 
> I've changed the headers so that the contig name is "name of strain" + "_" + "contig #"
> Example:
> 
> > GCA_123456789.1_1
> > GCA_123456789.1_2
> > ...
> > GCA_123456789.1_50
> 
> The contig Description is unchanged.
> 
> When the FASTA file containing these altered headers is run through antismash, I get this gbk output format:
> 
> c00001_GCA_123...region001.gbk
> c00002_GCA_123...region001.gbk
> ...
> 
> Any help?

I just made the header name shorter and it worked fine. But I still think the option would be a great idea!
