### ISSUE TITLE
How reliable is the "Most similar known cluster" column?

### ISSUE THREAD

**Issue by Lamm-a** [antismash/antismash#238]
The "Most similar known cluster" provides a % similarity to a significant BCG hit in blast but when that column returns say 3% or even 30%, is that really enough to take away that this BGC might produce that compound? Sorry if I am misunderstanding the purpose of that output.

**Comment by kblin** [comment]
The purpose of the output is to tell you which entries in the MIBiG database are similar to the region you're currently looking at, based on sequence similarity using the ClusterBlast algorithm described in http://dx.doi.org/10.1093/nar/gkr466
There's no hard and fast rule when a cluster is "close" enough to assume it's the same compound.
It's still a useful tool in general, which is why we run it.

**Comment by Lamm-a** [comment]
Okay thank you :) what can be further done to determine the role of a BGC identified by antismash?

**Comment by kblin** [comment]
If there's nothing else you know about the cluster, that's where the wet lab part starts.

**Comment by Lamm-a** [comment]
Ah okay . Would blasting the NCBI NT database with conserved regions of the BCG identified in subclusterblast not provide any extra info? 

Also what is the difference between the clusterblast and knowncluster blast output .txt files?
