### ISSUE TITLE
Best way to generate a datatable of information represented in the html output ?

### ISSUE THREAD

**Issue by Lamm-a** [antismash/antismash#240]
Whilst the htlm output it very useful to look at, having a tabular version of it would be more useful for generating summaries across samples or groups of samples and just general use in down stread analysis. I know you used to have the genecluster.txt output but no longer generate that so what is the best way to get such a tabular output now?

**Comment by kblin** [comment]
We no longer generate the geneclusters.txt file because the format did not accommodate the updated region concept in a meaningful way.

All the data is in the JSON output file in a machine-readable format, you can extract in information relevant to your research question from that. There's tons of resources on how to work with JSON data on the internet.

**Comment by Lamm-a** [comment]
Okay thanks, to be sure, the JSON you would refer to in <sample name>.json?

**Comment by kblin** [comment]
yes

**Comment by Lamm-a** [comment]
This also has the whole sequence at the top of the json file right?

**Comment by kblin** [comment]
Yes, the whole point of that file is to allow antiSMASH to re-use previous results when re-running with different parameters. It has all the data.

**Comment by Lamm-a** [comment]
Do you have any advice on how to best scrape the json file for information on identified clusters, similarity, regions and such.
