### ISSUE TITLE
multiple CDS features have the same name for mapping!

### ISSUE THREAD

**Issue by sunnycqcn** [antismash/antismash#252]
Hello,
I met a error when I run antismash 5 as following:
/home/AAFC-AAC/fuf/miniconda3/envs/antismash/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
ERROR    28/03 10:00:18   multiple CDS features have the same name for mapping: L092_011211
Then I used command grep check the L092_011211, the gene information as following:
/locus_tag="L092_011211"
                     /locus_tag="L092_011211"
                     /locus_tag="L092_011211"
                     /locus_tag="L092_011211"
                     /protein_id="ncbi:L092_011211-T3"
                     /locus_tag="L092_011211"
                     /protein_id="ncbi:L092_011211-T2"
                     /locus_tag="L092_011211"
                     /locus_tag="L092_011211"
                     /locus_tag="L092_011211"
                     /locus_tag="L092_011211"
                     /protein_id="ncbi:L092_011211-T1"
                     /locus_tag="L092_011211"
                     /protein_id="ncbi:L092_011211-T5"
                     /locus_tag="L092_011211"
                     /protein_id="ncbi:L092_011211-T4"
It should be alternative splicing.
Could you help me check how to figure out this err? I had run more than 100 isolates. Only this one met this err.
Thanks,
Fuyou

**Comment by SJShaw** [comment]
Required locus tags/gene identifiers to be unique within a record/contig was a deliberate choice when we were designing antiSMASH 5. If there's multiple genes with the same locus tag, we're unable to refer to genes by locus tag in the output, which leads to confusion. We chose not to rename in this scenario because it also leads to confusion in the output.

Splice variants are rare enough that we didn't consider them at the time. You can work around it by renaming the variants (e.g. `L092_011211-A`, `L0-2_011211-B`, etc).

**Comment by BenjaminSchwessinger** [comment]
I had the same issues for fungi that were annotated with funannotate. I wonder if "protein_id" would be the better identifier to check. According to NCBI locus_tags are to be used as follows.

"The same locus_tag should be used for all components of a single gene. For example, all of the exons, CDS, mRNA and gene features for a particular gene would have the same locus_tag."

From here https://www.ncbi.nlm.nih.gov/genbank/eukaryotic_genome_submission_annotation/#locus_tag. So renaming the locus_tags in a gbk makes it non-compliant with NCBI standards. 

For now I am trying to get around this with supplying the genome and a gff3 instead of a gbk file.

**Comment by jimie0311** [comment]
Hi Benjamin,
Have you solved this issue? I tried gff3, however, the error came up: Unknown file format '.gff3'

**Comment by kblin** [comment]
In order to run antiSMASH with annotations from GFF, you need to run with the sequence in a FASTA file, and then use `--genefinding-gff yourGffFileHere.gff` to specify that you want to use the GFF file to provide gene annotations.

**Comment by jae0326** [comment]
I solved this by using earlier version of antiSMASH in the standalone on Linux.
