### ISSUE TITLE
Possibility to install databases from antismash git

### ISSUE THREAD

**Issue by felipelira** [antismash/antismash#254]
**Is your feature request related to a problem? Please describe.**
I tried to use the download-antismash-database as recommended at https://docs.antismash.secondarymetabolites.org/install/#installing-the-latest-antismash-release but it depends of the availability of Pfam server/ftp to download and install it. If it's not available, we can go further.

**Describe the solution you'd like**
I understand that it is not easy to deal but if you store these databases in some git, ftp, or repository, it would be able to install without the need to count with the third part ftp's.

**Comment by SJShaw** [comment]
I don't think that we can really offer a mirror with an uptime that's better than the official sites (ResFam and Pfam). We do host the clusterblast database, because that's our own creation, but the downtime for the external sites is rare enough that's not really worth the time investment for us, given that it's only really needed once per install (and again once every year or two when the relevant databases update).

These databases also too large to justify putting into a git repository (especially this one), as the change tracking alone will cause the repository to be much, much larger than necessary.
