### ISSUE TITLE
Similarity scores from knownclusterblastoutput.txt output

### ISSUE THREAD

**Issue by adityabandla** [antismash/antismash#291]
Currently, I can see similarity scores displayed in the HTML output under most similar known clusters. Is there a way to calculate this programatically from the knownclusterblastoutput.txt file from a command-line run? I checked the publication to see how S is calculated and would like to know if knownclusterblastoutput.txt already has all the info to calculate this separately?

Also interested to know if there are any parsers in secmet which can do this?

**Comment by SJShaw** [comment]
The knownclusterblastoutput.txt is a legacy output file that only records the hits themselves. It alone will not have enough information to recalculate the scores. 

If you want to find the full breakdown of the scoring as per the paper's description, it will be in the results JSON in a path like: `records[(record_index, e.g. 0)]["modules"]["antismash.modules.clusterblast"]["knowncluster"]["results"][(a list of region results)]["ranking"][0]`. That will give you a tuple of two items, the first being the details of the highest ranked known cluster, the second being a breakdown of the score components and each matching hit.

The "similarity" shown in the HTML output is unrelated to that ranking score, it's just a percentage of genes in the reference cluster with some match to at least one gene in the query region (you can regenerate that similarity by using the scoring info from the JSON as above). It's misleading enough that we're looking at alternative methods of doing these comparisons and similarity scoring right now.

The parsing abilities of `antismash.secmet` are generally restricted to conversions to and from biopython/genbank.

**Comment by adityabandla** [comment]
@SJShaw Thanks for this informations, it's helpful. When trying to find MIBiG clusters similar to query clusters, is similarity score as proposed in the ANTISMASH 2011 paper the way to go or is the one displayed in the HTML sufficient (I would think otherwise?)

**Comment by SJShaw** [comment]
The rankings in the HTML output use the 2011 paper's scoring system. The most similar cluster on the overview page is the same as the highest ranked cluster. However, the percentage similarity is a different calculation for each, so you can have a 100% similarity cluster with a lower rank than a 90% similarity cluster in the right conditions.

For some cluster types, that ranking method seems to be fine, but for others (e.g. Type I PKS and NRPS clusters), the blast score alone isn't quite enough due to the modular components being present in widely varying types (e.g. both T1PKS and trans-AT PKS clusters scoring well against each other because all modules all sharing a ketosynthase and transporter, regardless of the presence of the acyltransferase).

If you can wait two or three months, the replacement comparison system that takes into account the non-blast components of cluster comparison should be ready to use.

**Comment by SJShaw** [comment]
Closing this due to age.
The alternative mentioned above was also released in antiSMASH 6.0 (65601a9d).
