### ISSUE TITLE
How to  generate "unique record identifiers" in order to run combiner.py to summarize several runs

### ISSUE THREAD

**Issue by drelo** [antismash/antismash#318]
**Describe the bug**

I am currently using antiSMASH 5.1.2 in a cluster, I obtained 44 results from metagenomes and I wanted 
I don't have expertise handling JSON files but I found you can use the [combined.py  script] written by (https://github.com/antismash/antismash/issues/180) written by @SJShaw to combine several runs. I tried to use this, but it seems I have identical identifiers.

`/combiner.py combine.json CAR-16.json CN-16.json 
duplicate record ids: c00001_NODE_1_..`

**Expected behavior**

Is there a way to change those identifiers (preferably in _bash_ or _R_) or even re-run the analysis to get those "unique record identifiers". I am new to JSON outputs but maybe I can parse these files in R with jsonlite or similar tools. 

**To Reproduce**

I used a line like this to run each sample `antismash ../METAG/CN-16.fasta --cb-knownclusters --genefinding-tool prodigal-m -c 40 --smcog-trees --html-title CN-16 --output-dir OUT/CN-16
`

You can find subsample of my whole set, 2 json files compressed as tar.gz https://drive.google.com/file/d/1QogbI-Vqpx7-A4LDqLM7SQPapMMP3PXH/view?usp=sharing

Thanks for your help.

**System (please complete the following information):**
 - OS: CentOS and Ubuntu 18.04
 - Browser: Chrome

**Comment by SJShaw** [comment]
This one is a bit tricky. While antiSMASH ensures that all the record identifiers are unique per run, it can't do it across multiple runs. If you know all your contig names are unique across all your inputs and you're ok with the length of them potentially breaking the genbank output, you can use the `--allow-long-headers` option to stop antiSMASH renaming due to length.

The only other suggestion I'd have would be to use `sed` to essentially find and replace the shortened names throughout the entire JSON result with some new identifier you know to be unique for all your inputs. It'd look something like `sed -i -e 's/existing_name/new_unique_name/g' result.json`

**Comment by drelo** [comment]
Thanks for your help! I didn't have the latest version available at the cluster so I ended rerunning it with a collection of fasta files with ids shorter than the output from SPAdes, then I did the combiner.py and reuse step and it worked fine.
