### ISSUE TITLE
Antismash ran out of memory while processing multiple genomes

### ISSUE THREAD

**Issue by hites77** [antismash/antismash#329]
When trying to run antismash for multiple genomes (in fasta format) by submitting jobs in cluster, after running few genomes the antismash halt stating that : memory exceeded limit

Does the antismash keep piling previous run in system memory.
Any way to assign temporary folder or clear memory.

**Comment by SJShaw** [comment]
If you are running one genome at a time, the previous runs have no impact on memory use unless you're not letting them complete. After antiSMASH exits from a run, it cannot hold onto memory, as no operating system allows anything like that for good reason.

It won't change memory use, but if you want to change your temporary directory, you can do that with your relevant operating system's settings or environment variables.

How much memory does your system have, what's the size of the input you're providing, and which analyses are you running with?

**Comment by hites77** [comment]
My hpc cluster has 160Gb memory

I am processing around 400 genomes with this command:
for file in *.fna; do antismash -c 80 --genefinding-tool prodigal --asf --cb-general --cb-subclusters --cb-knownclusters --pfam2go $file;done

**Comment by SJShaw** [comment]
After each of those antiSMASH runs, the memory should be freed by your operating system. This is not something antiSMASH has any control over at all, so if it is the issue we can't help.

I ran on NC_003888 as a fasta input (~9 megabases) with the same options (including core counts) on compute node here and no more than ~12Gb of RAM was actually used. It's possible your inputs may be the cause if they're very large. You didn't answer that question so I'll assume it's confidential.

There's two other possibilities that I can think of that aren't directly related to your input:
- the high core count and python parallelism not easily using copy-on-write
- there's some issue on that machine in environment or setup that isn't the same as my test above

Using 80 cores will use more memory than lower core counts, due to how python parallelism tends to work. It's also unlikely to be much faster than a 16 core run (and may even be slower), thanks to Amdahl's law and the sequential portions of the analysis. Try with a lower core count and see if that does anything.

If it still doesn't help, some information about the system you're running on would be needed to help further.

**Comment by hites77** [comment]
Thanks Shaw, reducing the number of core to 20 solved the issue for now, for the first time antismash crossed the analysis of 100 genomes; Also got an idea about Amdahl's law :-)
