### ISSUE TITLE
--genefinding-gff3 fails with GFF3 that includes a valid ##FASTA sequence section

### ISSUE THREAD

**Issue by hillan141** [antismash/antismash#364]
**Describe the bug**
When I submit a Prokka-generated GFF file that includes a ##FASTA sequence section, `antismash` fails with message "could not parse records from GFF3 file"

**Expected behavior**
I'd expected that Prokka-generated GFF files would be valid inputs to `antismash`.

**To Reproduce**
* Execute Prokka on a genomic fasta.  
* In the output .gff, observe a ##FASTA sequence section at the end of the file matching the GFF3 standard: http://gmod.org/wiki/GFF3#GFF3_Sequence_Section
* Submit the .gff as --genefinding-gff3 to `antismash`
* Observe the run fails with error message:

```
ERROR    28/05 22:00:49   read() takes 1 positional argument but 2 were given
ERROR    28/05 22:00:49   could not parse records from GFF3 file
```

**Screenshots**
n/a

**System (please complete the following information):**
 - OS: Ubuntu 
 - antismash 6.0.0alpha1

**Additional context**
A workaround that removes the ##FASTA section from the Prokka gff is of course possible.  My understanding though is that Prokka is widely used and will incude this section in output GFFs.  If that is the case it would be nice to support that in `antismash`.  Thanks for creating and supporting `antismash`!

**Comment by kblin** [comment]
Hi there, thanks for letting us know. I haven't dug into this yet, but my first suspect is the GFF parsing library that we use for this. Having said that, Prokka should create a GenBank file in addition to the GFF file, so maybe using that is another workaround that's less work than removing the `##FASTA` section.

**Comment by hillan141** [comment]
Thanks, and good point about the Prokka-generated GenBank file.

**Comment by SJShaw** [comment]
This has been fixed in a recent version of the `bcbio-gff` dependency. If you update that package you should be able to use these GFF inputs that include the sequence.

**Comment by ezequielnaftali** [comment]
same problem here. Working with antismash 6.1.1 but not with 7.1

**Comment by fconstancias** [comment]
I am having the same issue with antiSMASH 7.1.0 installed though conda

**Comment by ufaroooq** [comment]
Leaving this here as an Update for anyone who faces this issue.

IF you are using `antismash v7.1.0` then it installs `bcbio-gff v0.7.1` which generates that "unable to parse gff file" error.
downgrade it to v0.6.9 (was mentioned in issue #796 )

> I experienced a similar issue. I downgraded from version 7.1.0 to 7.0.0 and reinstalled, but the same problem occurred. Referring to a previously closed issue, I determined that the problem was with bcbio-gff. When I downgraded the bcbio-gff version to 6.9.0 in my conda environment, the issue was resolved. 

 _Originally posted by @hope9901 in [#796](https://github.com/antismash/antismash/issues/796#issuecomment-2735061711)_

I have `antiSMASH 7.1.0` installed in conda environment.
Initially i was running antiSMASH fungi on Funannotate generated .gbk file but it generated errors due to presence of multiple isoforms. 
For that use `agat_sp_keep_longest_isoform.pl -f your_input.gff3 -o your_output.gff3`
then run antiSMASH using thie new `.gff3` file along with `.fa` file.

works great now.

my command
```
antismash \
    $input_fa \
    --taxon fungi --cpus 94 --debug --verbose --genefinding-tool none \
    --fullhmmer --cassis --clusterhmmer --tigrfam --asf --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --pfam2go --rre --smcog-trees --tfbs \
    --output-basename ${species}_${strain}.antismash --output-dir $Fanno_out/antismash_results \
    --genefinding-gff3 $input_gff
```
