### ISSUE TITLE
solution to #169 for "full manual install"?

### ISSUE THREAD

**Issue by mmp3** [antismash/antismash#372]
Is there an analog to the solution to #169 for the "full manual install" option?

Specifically:

```
$ antismash  --check-prereqs
ERROR    21/06 13:35:40   antismash.detection.cassis: preqrequisite failure: Failed to locate executable for 'meme'
ERROR    21/06 13:35:40   antismash.detection.cassis: preqrequisite failure: Failed to locate executable for 'fimo'
Some module prerequisites not satisfied
```

But I do not have a license for the `meme` suite.

The solution to #169 was to change a line in the Docker script, from 

```
    antismash/standalone:5.0.0 \
```

to

```
    antismash/standalone-nonfree:5.0.0 \
```

**Comment by kblin** [comment]
The solution you mentioned there requires a meme suite license. You can run the RiPP modules without `fimo` when you specifiy `--without-fimo`, but there's no way around `meme` and `fimo` if you want to run CASSIS on fungal sequences. That's why that dependency check is there. If you run `--without-fimo` and don't run CASSIS, you can safely ignore this.
