### ISSUE TITLE
[Question] - How to use antiSmash with pre-computed gene annotations

### ISSUE THREAD

**Issue by tamuanand** [antismash/antismash#376]
Hi

I have a question on running AntiSmash 6.0.1 with `--genefinding-tool none`.  

If I have my gene calls (using PGAP)  as a gbk file for a specific assembly, when using `--genefinding-tool none`  which of the below do I need to provide to `antismash` command line

1. provide only the gbk file
2. provide both the assembly fasta file and the gbk file 

Based on my reading of [this issue](https://github.com/antismash/antismash/issues/364#issuecomment-850788872), I would think Option 1 above (providing gbk file alone) would suffice.

Please advise.

Thanks in advance.

**Comment by SJShaw** [comment]
The primary input file can be either a Genbank or a FASTA file, but only one can be provided. If your Genbank file does not include the sequence information from the FASTA file, you'll need to include that in your Genbank file.

**Comment by tamuanand** [comment]
@SJShaw 

Thanks for clarifying the same.

A follow up question: If I have a AntiSmash 5.2.1 final output genbank file, can I use that file as a query file to AntiSmash 6 with `--gene-finding-tool prodigal` 

A related but different question: I realize `prodigal-m` is for metagenomic data. Just curious to know from your end, 
- how would results be different if `prodigal` was used on metagenomic data instead of `prodigal-m`. What differences should one look out for
- Do you have any such analysis/findings 

Thanks

**Comment by SJShaw** [comment]
Sorry for the delay in responding.

You can use an antiSMASH output genbank as an input file. Any features that were created by antiSMASH will be stripped for the new run, so specifying `--genefinding-tool` will be necessary to recreate those.

As for the metagenomic portion, the typical uses I've had aren't metagenomes and I don't have any such inputs to use as test cases where I know what to expect from them. The [prodigal wiki](https://github.com/hyattpd/prodigal/wiki/Advice-by-Input-Type#metagenomes) might be of more use than I am, since it has an advice section for metagenomic inputs (`prodigal-m` is equivalent to "anonymous mode" in the documentation, as the `meta` option is deprecated).
