### ISSUE TITLE
A way to redirect temporary files during antiSMASH run?

### ISSUE THREAD

**Issue by mhyleung** [antismash/antismash#402]
**Describe the bug**
Default location of temporary files ran out of space, and antiSMASH run interrupted.

**Expected behavior**
I expect a way to set where temporary files will be stored as an option during antiSMASH command run

**To Reproduce**
not applicable

For interaction issues, also include steps to reproduce the behavior:
Not applicable

**Screenshots**
Not applicable

**System (please complete the following information):**
 - OS: [e.g. iOS, Ubuntu] Ubuntu
 - Browser [e.g. chrome, safari] (if relevant)

**Comment by SJShaw** [comment]
Since all temporary files usage within antiSMASH uses the `tempfile` standard library, this can already be done by setting the [TMPDIR](https://en.wikipedia.org/wiki/TMPDIR) environment variable to the directory you'd like to use as a temporary directory.

Here's an example on an ubuntu system using the default shell (BASH) with `tempfile.gettempdir()` to find the current temporary directory (see [here](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir) for details):
```
# print the default location
$ python3 -c "import tempfile; print(tempfile.gettempdir())"
/tmp

# change the location for a single command (the new path must exist as a directory for this to work)
$ TMPDIR=/some/other/dir python3 -c "import tempfile; print(tempfile.gettempdir())"
/some/other/dir
# returns to the default location
$ python3 -c "import tempfile; print(tempfile.gettempdir())"
/tmp

# run antiSMASH with a custom temporary directory
$ TMPDIR=/some/other/dir antismash your_input.gbk
```

There's other ways of setting the environment variable and you can make the change for the rest of the shell session or even for every session, but that's not in the scope of what antiSMASH needs to know about or handle, since it will all be treated the same way.
