### ISSUE TITLE
Restart the antismash run from mid results

### ISSUE THREAD

**Issue by pdhrati02** [antismash/antismash#419]
Hi, 
I was running antismash on about 1500 assembled genomes and it was running for several days. But due to some issue we had to stop that run. I wish to restart the run from where it stopped instead of repeating the analysis for the samples which are already done. 
Is there an option in antismash which would allow to do so? Such as bypass already run samples ? 

Or do we have to rerun everything from the start?

Any help would be appreciated.

Thank you
DP

**Comment by SJShaw** [comment]
Is this 1500 genomes in a single input file? If so, no, there's nothing in antiSMASH for this because it's not really intended to generate a massive 1500 genome result file.
If you want to run that many, you can run the individual genomes and then combine the results. I wrote [this script](https://gist.github.com/SJShaw/67b438c58d1f83ed261ca177b6035951) for someone who wanted to combine antiSMASH 5 results, and those should be close enough to current results for this purpose at least. You could then generate new genbanks/HTML by passing the `--reuse-results` option and the resulting JSON file.

If they're individual files, you can have a script check for the output directory and for an `index.html` file so you know it completed and you can skip it. If the HTML wasn't generated, it failed and you can delete the directory and start that genome again.

**Comment by pdhrati02** [comment]
Hi @SJShaw Thank you very much. They are individual files and so I was getting individual folder outputs. Thank you very much for the suggestion about the script in loop to check for output files, I will try doing this. Thank you once again for all your help.
DP
