### ISSUE TITLE
Orig. start can't locate at 1

### ISSUE THREAD

**Issue by JamesWZM** [antismash/antismash#430]
**Describe the bug**
I'm using antismash docker version 5.1.1. On this sequence, I found that the first feature of this gb file after antismash marked features is not gene or CDS, but is a CDS_motif. I'm sure that this is becouse the 'Orig. start' should be 1 and there's an index movement.
I'm not sure will this only happens when the 'Orig. start' should be 1. Also, this problem might has been solved on higher version.

**To Reproduce**
Genbank accession: GCA_016741855.1_ASM1674185v1_genomic

**Screenshots**
![image](https://user-images.githubusercontent.com/48663928/159898727-246b8756-9eec-4032-baa9-e648bc3f1ecf.png)
![image](https://user-images.githubusercontent.com/48663928/159901241-d5469e12-5016-4d9f-9954-b87aa9093f4d.png)

**Comment by SJShaw** [comment]
There was an off-by-one in the region genbank comment start location that was fixed in 1600e403 nearly three years ago.

The ordering of features has also changed since 5.1.1, it should now be sorted by start position and overall length of the feature. The first feature in a region genbank file will never be a gene or CDS under these rules.
