### ISSUE TITLE
Thiopeptides: no precursor peptide predictions

### ISSUE THREAD

**Issue by snayfach** [antismash/antismash#440]
** This is a question, not a bug **

In the Antismash 6 paper it says: 
> for lanthipeptide, lasso peptide, sactipeptide, and thiopeptide BGCs, antiSMASH provides more detailed product predictions by detecting the cluster's prepeptide and commonly occurring tailoring enzymes

However I never see prepeptide and tailoring enzyme predictions for thiopeptides. I also can't seem to find thiopeptides with this information in https://antismash-db.secondarymetabolites.org. I'm running an alpha version of Antismash 6.

Is this behavior expected? And out of curiosity, why does Antismash not report this information for other classes of RiPP BGCs?

**Comment by SJShaw** [comment]
Not every thiopeptide protocluster will have a matching prepetide. There may be no suitable genes, the genes found may score too badly, and so on. The [nosiheptide](https://mibig.secondarymetabolites.org/repository/BGC0000610/generated/index.html#r1c1) cluster from [FJ438820.1](https://www.ncbi.nlm.nih.gov/nuccore/FJ438820.1) has predictions for the thiopeptide, as an example.

When the genes are missing (generally because they're considered too small by prodigal and other gene finders), there's a system that should find them down to a much smaller size, but it seems like that part may not be functioning quite as expected. This could be responsible for more thiopeptides missing predictions than should be expected, but that will take a little investigation.

Since the various RiPP analysis modules in antiSMASH are all tailored to specific types of RiPP, the predictions made for one type won't generally be the same as for the others.

**Comment by snayfach** [comment]
Thanks for the response.

Is there a good way that I can check if my version of antismash is running the module to detect short genes? For a bit more context, I have ~6000 thiopeptides in my database and not a single one has a predicted prepeptide.

**Comment by SJShaw** [comment]
If it found a thiopeptide protocluster and ran the thiopeptide module at all, it searched for these genes. There's restrictions on when it adds them though, they have to have a decent score as a precursor, they can't overlap with existing CDS features, and so on.
