### ISSUE TITLE
Genefinding prodigal

### ISSUE THREAD

**Issue by INFINITY1993** [antismash/antismash#446]
**Is your feature request related to a problem? Please describe.**

1. I am running  "--genefinding-tool prodigal" in antismash 6.0, whereas I noticed that the antismash still use "-p meta" when running prodigal. why?

2. I am annotating the BGCs in MAGs (assembly by metaspades, and binning by metabat2, minimum scaffold length > 2,000bp) using antismash, so should I treat the MAGs as metagenome or single genome? although people have raised the similar question, there seems no clear explanation about this issue.

Big thanks in advance!

![image](https://user-images.githubusercontent.com/63569349/168203065-111e3ef6-6940-42a0-a212-f3fde3af2880.png)

**Comment by SJShaw** [comment]
It's assumed that any contig less than 20kb is a metagenomic input.
https://github.com/antismash/antismash/blob/fc634b513c26d4e8ea8de4df4f74a809ad6b8977/antismash/support/genefinding/run_prodigal.py#L37-L38

Metagenomic inputs to antiSMASH are unlikely to give you good results. This is because the more fragmented a genome is, the more likely interesting areas will be missed, and will likely be truncated even if detected. This applies to poor assemblies of single genomes as well as metagenomic inputs, since it's extremely common for metagenomic inputs to be fragmented beyond meaning in terms of genomic context.

**Comment by INFINITY1993** [comment]
Thanks for your reply. It is helpful!

**Comment by INFINITY1993** [comment]
Thanks for your reply. It is helpful!
