### ISSUE TITLE
Problem to install antismash in bioconda environment 

### ISSUE THREAD

**Issue by catluna53** [antismash/antismash#566]
Hi! I am trying to install antismash but I have this problem. I have a MacBook Air with macOS Monterey version 12.6.3. Processor 1,8 GHz Dual-Core Intel Core i5 and 8 GB memory. Does anybody know how could I fix it?. I have include the message that appears in my terminal:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/osx-64::__osx==10.16=0
  - feature:|@/osx-64::__osx==10.16=0
  - antismash -> matplotlib-base -> __osx[version='>=10.11|>=10.12']

Your installed version is: 10.16

Note that strict channel priority may have removed packages required for satisfiability.

**Comment by SJShaw** [comment]
If you already have some of these dependencies installed in your current conda environment and they're a different version, then you will get this.

You may also have installed some packages in your `base` environment that can cause these kinds of conflicts even when you've activated another environment. This is standard conda behaviour.

If you have nothing installed in your base environment and you're using a clean environment, it will likely be a problem with conda specifically trying to support your machine type. This would be something that needs to be raised with the conda folks rather than us. Our only real solution there would be for you to install only the binary dependencies via conda and then just use pip to install the python portions, which is far more flexible.
