### ISSUE TITLE
Nucleotide sequence changes in BGC GenBank relative to genome

### ISSUE THREAD

**Issue by raufs** [antismash/antismash#591]
Sorry if this has already been asked and I am not sure if this is actually a bug or an expected feature, but I noticed that in rare cases the nucleotide sequence for a BGC changes to what it is reported in the input genome.

As an example, if antiSMASH is run on the web or commandline for CP009623.1, we see that the first BGC prediction from coordinates 1,172,251 to 1,192,951, has an N in the nucleotide sequence of the individual BGC prediction's GenBank that is not present in the original nucleotide sequence for CP009623.1 as found in NCBI's nucleotide database.

**Comment by SJShaw** [comment]
The specific base that changes to `N` is originally a `W`, which is already ambiguous. The change to `N` is intentional, as it won't affect gene translations, won't allow for any extra ORFs to be found, and won't count as an `A` or `T` (in this specific case) for external tools like MOODS (used by the TFBS module in antiSMASH).

If you want those ambiguous bases to persist throughout the runs, you can use the `--skip-sanitisation` argument when running with your local install.

**Comment by raufs** [comment]
Awesome, thank you so much for the clarification and quick response!

Appreciate it!
Rauf
