### ISSUE TITLE
antismash-7.0 diamond fails makedb during download-antismash-database

### ISSUE THREAD

**Issue by kgh03** [antismash/antismash#609]
**Describe the bug**
when building antismash-7.0, 
diamond fails makedb during download-antismash-database.

**Expected behavior**
diamond succeeds makedb phase. 

**To Reproduce**
```
conda create -p /data/conda/antismash7dl python=3.11
conda install hmmer2 hmmer diamond fasttree prodigal blast muscle glimmerhmm
conda activate /data/conda/antismash7dl
wget https://dl.secondarymetabolites.org/releases/7.0.0/antismash-7.0.0.tar.gz
tar xzvf antismash-7.0.0.tar.gz
pip install antismash-7.0.0
python -i $(which download-antismash-database)

Error encountered while preparing module data: diamond failed to run: makedb
Traceback (most recent call last):
  File "/data/conda/antismash7dl/lib/python3.11/site-packages/antismash/download_databases.py", line 526, in _main
    antismash.main.prepare_module_data()
  File "/data/conda/antismash7dl/lib/python3.11/site-packages/antismash/main.py", line 580, in prepare_module_data
    module.prepare_data()
  File "/data/conda/antismash7dl/lib/python3.11/site-packages/antismash/modules/cluster_compare/__init__.py", line 122, in prepare_data
    failure_messages.extend(check_diamond_files(cluster_defs, protein_seqs,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/conda/antismash7dl/lib/python3.11/site-packages/antismash/common/subprocessing/diamond.py", line 192, in check_diamond_files
    elif not check_diamond_db_compatible(db_file):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/conda/antismash7dl/lib/python3.11/site-packages/antismash/common/subprocessing/diamond.py", line 125, in check_diamond_db_compatible
    run_diamond_makedb(dummy_db, dummy_fasta)
  File "/data/conda/antismash7dl/lib/python3.11/site-packages/antismash/common/subprocessing/diamond.py", line 92, in run_diamond_makedb
    return run_diamond("makedb", args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/conda/antismash7dl/lib/python3.11/site-packages/antismash/common/subprocessing/diamond.py", line 48, in run_diamond
    raise RuntimeError(message)
RuntimeError: diamond failed to run: makedb

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/conda/antismash7dl/bin/download-antismash-databases", line 8, in <module>
    sys.exit(_main())
             ^^^^^^^
  File "/data/conda/antismash7dl/lib/python3.11/site-packages/antismash/download_databases.py", line 530, in _main
    sys.exit(1)
SystemExit: 1
>>>

```

**Screenshots**

**System (please complete the following information):**
 -- ubuntu 18.04 with anaconda python 3.11, downloaded antismash7.0 installing via pip. 

**Additional context**
it had initially stalled on the proteins data, so i ran it manually and it worked but then it seems to want to run daimond on some dummy data and either it cant find it or isn't forming a diamond call or something.
,,,
diamond makedb --db /data/conda/envs/antismash7dl/lib/python3.11/site-packages/antismash/databases/clustercompare/mibig/3.1/proteins.dmnd --in /data/conda/envs/antismash7dl/lib/python3.11/site-packages/antismash/databases/clustercompare/mibig/3.1/proteins.fasta
,,.

**Comment by SJShaw** [comment]
That dummy FASTA is a simple two line file that was written immediately before the failing diamond call (and successfully, unless there's something very non-standard about your python). It's used to determine diamond's binary encoding of version and then check if the same version of diamond was used to build a database as will be used to queries.

Since there was no output from diamond on stderr, that makes it much harder to work out what's going wrong. 

If diamond failed to make that dummy database, then there's very few causes I can think of:
- there is a problem with your diamond or your specific version of diamond rejects that small test file as a valid input
- the diamond you're using within the python process environment isn't actually diamond but a similarly named but different executable
- the permissions on the temporary directory that's created are somehow write-only, instead of a more normal read/write
- the filesystem is full or has otherwise hit a limit (e.g. a user quota)

For the first option, we've tested antiSMASH with a wide variety of diamond versions and haven't seen this, so we'd need to know what version of diamond you have installed.
For the second, you can run antiSMASH with the command line option `--executables diamond=/your/path/to/diamond` to ensure it's using the diamond you're expecting. You can end up in the same data prepration steps by adding `--check-prereqs`, for easier testing.
For the last two options, you'll need to check your system. If either are the cause, then you will hit a great many more problems within antiSMASH than just running diamond.
