### ISSUE TITLE
Antismash 7.0.0 docker compiled with avx2/avx512 requirement?

### ISSUE THREAD

**Issue by MarkiyanSV** [antismash/antismash#624]
I'm having trouble with running latest docker image on antismash 7.0.0 on my hosts, while the antismash 6.0.0 is working without problems on them. It looks like version packaged with docker had been compiled with march=native on the latest cpu.

In both cases docker image was pulled with the following command:

docker pull antismash/standalone-nonfree:7.0.0

When trying to run docker version of antismash 7.0.0 on HP DL580 G7 (CPU: 4xXeon E7-8837@2.67GHz, RAM 768GB)
Ubuntu LTS 18.04
I get the following error:

Running antiSMASH FAILED                                                                                                                             
/usr/local/bin/run: line 9:     6 Illegal instruction     (core dumped) antismash $@ /input/${INFILE}

I even can't get the help for antismash, and the following python code fails inside the container:

root@5d5ab3469dbb:/etc# python3 -c "import re;import sys;from antismash.__main__ import entrypoint;print('ok')"
Illegal instruction (core dumped)

So it looks like someone had compiled it with AVX flags (or march=native)

And when trying it on a bit newer system (Lenovo S30, (CPU: 1xXeon E5-2690@2.90GHz, RAM: 128GB),
Ubuntu LTS 20.04
It starts processing the dataset, but later on still fails with:

Running antiSMASH FAILED
/usr/local/bin/run: line 9:     7 Illegal instruction     (core dumped) antismash $@ /input/${INFILE}

So running it on the CPU with AVX support does not solve the problem, it looks like it wants AVX2 or even AVX512 suport for some fancy latest intel Xeon CPU...

To reproduce - try running docker version of antismash on a host with nehalem or westmere CPU.

Please make sure to compile antismash modules used in docker with **march=westmere** or **march=nehalem** flags (and not march=native).

**Comment by kblin** [comment]
We built the antiSMASH 7.0.0 docker images on an 8 year old system. I can't check the exact version of the CPU right now because the system is currently down due to the hard drives having died of old age. So I doubt building it on "some fancy latest intel Xeon CPU" is the issue here. Additionally, docker containers for 6.0.0 were built on the exact same system (all the docker containers back to antiSMASH  3, in fact).

Let's see if we can identify the actual issue here. We switched the antiSMASH base image from Debian 10 to Debian 11, we're relying on a couple of external libraries that are installed from binary wheels, there's many parts that might cause this.

Having said that, I don't think I have a system available to reproduce the issue on, the oldest systems we run here are using Ivy Bridge architecture.

**Comment by kblin** [comment]
I just double-checked, and it turns out the oldest systems I have access to are Haswell, and for sure support `avx2`, but not `avx512`.

Anyway, if you can pinpoint which module is the one giving you grief, I can try to look into this.

**Comment by SJShaw** [comment]
One of our dependencies (`MOODS-python`) explicitly builds with `march=native`: https://github.com/jhkorhonen/MOODS/blob/master/python/setup.py#L11C1-L11C71

You'll need to get them to change that or rebuild that python package yourself within the container.
