### ISSUE TITLE
Possibility to disable auto-scroll on ORF click

### ISSUE THREAD

**Issue by bdelepine** [antismash/antismash#660]
Hi all,

As of 7.0.1, when you click on an ORF in the top cluster view (.region-svg-container), you automatically scroll down to the selected item in the "Gene/CDS overview" table (when "Gene overview" details tab is active). This is annoying on small screens since it will hide the top cluster view and the "Gene details" (right-column). On big screens, the view wiggles gently and no information is hidden, so that's okay.

I would like to have the possibility to disable this auto-scroll. I suggest to re-use the "Automatically zoom to filtered/selected features" button from the "Gene/CDS overview" such that, if set, all scrolls and zooms are prevented: both from clicks on the table (actual bahavior) and on the top cluster view (new behavior).

Alternatively, you may consider:
* a new button next to "reset view" and "zoom to selection" (.zoom-buttons).
* moving items in the table but never scrolling the view (i.e. dropping the auto-scroll feature).

I believe this behavior was introduced in 7.0.0.

HTH, best regards,

**Comment by SJShaw** [comment]
This has been fixed in the javascript as of it's [v0.13.7](https://github.com/antismash/antismash-js/commit/e5825b0a290ddc8759ebeeff8ffc4028bf4f5d6b) update. If you're using a local antiSMAS install, you can get the updated javascript by running `download-antismash-databases`, otherwise it will be included in the upcoming 7.1.0 release of antiSMASH.

**Comment by kblin** [comment]
Should be fixed in the current 7.1.0 release
