### ISSUE TITLE
hmmer version compatible with antismash 7.0.1

### ISSUE THREAD

**Issue by matthpich** [antismash/antismash#747]
**Describe the bug**
hmmscan used by antismash does not work with all hmm in antismash database because of incompatible hmm model x hmmer version
What hmmer version needs to be used?

**Expected behavior**
antismash should work fine with all downloaded databases

**To Reproduce**
- install antismash with mamba/conda > mamba install -n antismash_test bioconda::antismash
- download antismash databases
- check hmmscan version 3.4 > hmmscan -h |head -n 2
- run hmmscan > hmmscan smcogs.hmm test/Ecoli.fa
- error message

Error: File format problem, trying to open HMM file smcogs.hmm.
Opened smcogs

**System (please complete the following information):**
 - CentOS

**Additional context**

**Comment by SJShaw** [comment]
I'm unable to reproduce this with a freshly compiled 3.4:
```
$ hmmpress smcogs.hmm 
Working...    done.
Pressed and indexed 301 HMMs (301 names).
Models pressed into binary file:   smcogs.hmm.h3m
SSI index for binary model file:   smcogs.hmm.h3i
Profiles (MSV part) pressed into:  smcogs.hmm.h3f
Profiles (remainder) pressed into: smcogs.hmm.h3p

$ hmmscan smcogs.hmm nisin.fasta
# hmmscan :: search sequence(s) against a profile database
# HMMER 3.4 (Aug 2023); http://hmmer.org/
<...>
Query:       nisA|NisA|ADJ56352.1  [L=57]
Scores for complete sequence (score includes all domains):
<...>
```
Ensure you don't have a corrupted file, the md5sum of `smcogs.hmm` is `f787400d057dee49effa87e00ecc7430`.

`smcogs.hmm` hasn't been changed for the last 12 years. It was built with HMMER 3.0rc2 and since then has worked with all HMMER 3 versions shipped by Debian (my development OS and the OS used in the webservice workers), including 3.2 and currently 3.3.

**Comment by matthpich** [comment]
wow thanks for the prompt answer and thanks for taking the time to try to reproduce.

The problem came from my path being too long.
Shorter paths seem to work fine.
