### ISSUE TITLE
makeblastdb error: libnsl.so.1

### ISSUE THREAD

**Issue by ggavelis** [antismash/antismash#755]
Hello,

I'm encountering the following error when I try to download antismash v7.1.0 databases through the conda environment.

**My commands**
```
conda create -n antismash_7.1.0 -c bioconda antismash=7.1.0
source activate antismash_7.1.0
download-antismash-databases
```

**The error**
```
Error encountered while preparing module data: makeblastdb failed to run: ['/mnt/anaconda3a/envs/antismash_7.1.0/bin/makeblastdb',
 '-in', '/mnt/anaconda3a/envs/antismash_7.1.0/lib/python3.9/site-packages/antismash/databases/comparippson/asdb/4.0/cores.fa',
 '-out', '/mnt/anaconda3a/envs/antismash_7.1.0/lib/python3.9/site-packages/antismash/databases/comparippson/asdb/4.0/cores.fa', '-dbtype', 'prot'] -> /mnt/anaconda3a/envs/antismash_7.1.0/bin/makeblastdb
error while loading shared libraries:
**libnsl.so.1: cannot open shared object file: No such file or directory**
```

I verified that all the above file paths exist, so the problem might be with libnsl.so.1 itself.

I'm running this on a cluster, and the libnsl.so.1 error is the same across both conda modules installed by the admin.

I appreciate any help you can provide.

~Greg

**Comment by kblin** [comment]
This sounds like a conda issue you need to raise on the blast package there.

**Comment by SJShaw** [comment]
I agree, this is unrelated to antiSMASH.
If you can't run BLAST's `makeblastdb` by itself, antiSMASH can't function.

Your blast install cannot find the dynamically linked `nsl` library (itself a dependency of the NCBI C++ toolkit). Either there's something wrong with your shell environment (e.g. `LD_LIBRARY_PATH` being set incorrectly), you have mismatching compilations (64bit vs 32bit) or conda doesn't supply a statically compiled binary.

Either way, since your cluster admin has installed these for you, contact them about this. They'll have the context of their install, their system environments, and the ability to change the install.

**Comment by ggavelis** [comment]
Ah okay thanks, re-installing blast within the environment seems to have fixed it.

`conda install bioconda::blast`
